workflows:
  android_consumer_debug:
    name: Android APK – Consumer (Debug)
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Build APK from subdir
        script: |
          cd packages/app_consumer
          flutter create .
          flutter pub get
          flutter build apk --debug
    artifacts:
      - packages/app_consumer/build/app/outputs/flutter-apk/app-debug.apk
